version: '3.4'

services:
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          MSSQL_SA_PASSWORD: "1236fG543$"
          ACCEPT_EULA: "Y"
        ports:
          - "1434:1433"
        restart: always

    demodocker:
        image: ${DOCKER_REGISTRY-}demodocker
        build:
            context: .
            dockerfile: DemoDocker/Dockerfile
        ports:
          - "8000:80"
        depends_on:
          - sqlserver
        restart: always